# フラグメントを定義するがgraphql-goでは対応されていない
# fragment Post on Post {
#   id
#   title
# }

# fragment User on User {
#   id
#   name
#   posts {
#     ...Post
#   }
# }
"""
ルートの型
"""
schema {
  query: Query
  mutation: Mutation
}

interface Node {
  id: ID!
}

type Post implements Node {
  id: ID!
  content: String!
  author: User!
}

type User implements Node {
  id: ID!
  userName: String!
  displayName: String!
  bio: String!
  avatarURL: String!
}

type PostConnection {
  edges: [PostEdge!]!
  nodes: [Post!]!
}

type PostEdge {
  node: Post!
  cursor: ID!
}

type Query {
  user(id: ID!): User!
  posts(first: Int, after: String): PostConnection!
}

type Mutation {
  createPost(input: CreatePostInput!): CreatePostPayload! @tag(name: "post")
  login(input: LoginInput!): LoginPayload!
}

type LoginInput {
  email: String!
  password: String!
}

type LoginPayload {
  token: String
  userErrors: [UserError!]!
}

type CreatePostInput {
  content: String!
  authorId: ID!
}

type CreatePostPayload {
  post: Post!
}
