/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts/index'
import { Route as PostsIdIndexImport } from './routes/posts/$id/index'
import { Route as PostsIdEditImport } from './routes/posts/$id/edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIdIndexRoute = PostsIdIndexImport.update({
  id: '/posts/$id/',
  path: '/posts/$id/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIdEditRoute = PostsIdEditImport.update({
  id: '/posts/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$id/edit': {
      id: '/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof PostsIdEditImport
      parentRoute: typeof rootRoute
    }
    '/posts/$id/': {
      id: '/posts/$id/'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/posts/$id': typeof PostsIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/posts/$id': typeof PostsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/posts/$id/': typeof PostsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts' | '/posts/$id/edit' | '/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts' | '/posts/$id/edit' | '/posts/$id'
  id: '__root__' | '/' | '/posts/' | '/posts/$id/edit' | '/posts/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsIdEditRoute: typeof PostsIdEditRoute
  PostsIdIndexRoute: typeof PostsIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsIdEditRoute: PostsIdEditRoute,
  PostsIdIndexRoute: PostsIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/posts/",
        "/posts/$id/edit",
        "/posts/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/posts/": {
      "filePath": "posts/index.tsx"
    },
    "/posts/$id/edit": {
      "filePath": "posts/$id/edit.tsx"
    },
    "/posts/$id/": {
      "filePath": "posts/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
